# Generated by Django 4.0.4 on 2022-05-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackModels',
            new_name='FeedbackModel',
        ),
    ]
