# Generated by Django 4.0.4 on 2022-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_dressingroom_actor_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressingroom',
            name='number',
            field=models.IntegerField(default=2),
        ),
    ]
